// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -308904230;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__engine__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::engine::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__engine__player_analyze_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_analyze",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_track = <crate::api::engine::TrackSource>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_analyze(api_track)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_cache_size_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_cache_size",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_cache_size()?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_clear_cache_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_clear_cache",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_clear_cache()?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_device_profile_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_device_profile",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_device_profile()?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_download_full_model_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_download_full_model",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_download_full_model()?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::engine::PlayerEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_events(api_sink)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_init_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_init",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::engine::PlayerConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_init(api_config)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_is_cached_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_is_cached",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cache_key = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_is_cached(api_cache_key)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_model_download_progress_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_model_download_progress",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::engine::player_model_download_progress())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__player_output_devices_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_output_devices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_output_devices()?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_pause_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_pause",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_pause()?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_play_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_play",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_track = <crate::api::engine::TrackSource>::sse_decode(&mut deserializer);
            let api_start_ms = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_play(api_track, api_start_ms)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_prefetch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_prefetch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_track = <crate::api::engine::TrackSource>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_prefetch(api_track)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_resume_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_resume",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_resume()?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_seek_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_seek",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_position_ms = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_seek(api_position_ms)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_seek_by_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_seek_by",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_delta_ms = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_seek_by(api_delta_ms)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_set_analysis_model_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_analysis_model",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_model = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_set_analysis_model(api_model)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_set_automix_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_automix",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::engine::AutomixConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_set_automix(api_config)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_set_cache_limit_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_cache_limit",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_limit_mb = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::engine::player_set_cache_limit(api_limit_mb)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_set_next_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_next",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_track =
                <Option<crate::api::engine::TrackSource>>::sse_decode(&mut deserializer);
            let api_mode = <crate::api::engine::TransitionMode>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_set_next(api_track, api_mode)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_set_notifications_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_notifications",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_enabled = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_set_notifications(api_enabled)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_set_output_device_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_output_device",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::engine::player_set_output_device(api_device_id)?;
                        std::result::Result::Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__player_set_volume_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_set_volume",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_volume = <f32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_set_volume(api_volume)?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_stop_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_stop",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_stop()?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}
fn wire__crate__api__engine__player_toggle_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "player_toggle",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                (move || {
                    let output_ok = crate::api::engine::player_toggle()?;
                    std::result::Result::Ok(output_ok)
                })(),
            )
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::engine::PlayerEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::engine::AutomixConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_style = <crate::api::engine::AutomixStyle>::sse_decode(deserializer);
        let mut var_maxTempoChange = <f64>::sse_decode(deserializer);
        let mut var_preferredBars = <u32>::sse_decode(deserializer);
        let mut var_minBars = <u32>::sse_decode(deserializer);
        let mut var_maxSeconds = <f64>::sse_decode(deserializer);
        let mut var_unclearSeconds = <f64>::sse_decode(deserializer);
        let mut var_harmonic = <bool>::sse_decode(deserializer);
        let mut var_tempoRampBars = <u32>::sse_decode(deserializer);
        let mut var_trimSilence = <bool>::sse_decode(deserializer);
        return crate::api::engine::AutomixConfig {
            style: var_style,
            max_tempo_change: var_maxTempoChange,
            preferred_bars: var_preferredBars,
            min_bars: var_minBars,
            max_seconds: var_maxSeconds,
            unclear_seconds: var_unclearSeconds,
            harmonic: var_harmonic,
            tempo_ramp_bars: var_tempoRampBars,
            trim_silence: var_trimSilence,
        };
    }
}

impl SseDecode for crate::api::engine::AutomixStyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::engine::AutomixStyle::Auto,
            1 => crate::api::engine::AutomixStyle::BassSwap,
            2 => crate::api::engine::AutomixStyle::Blend,
            3 => crate::api::engine::AutomixStyle::Filter,
            4 => crate::api::engine::AutomixStyle::Echo,
            5 => crate::api::engine::AutomixStyle::Cut,
            _ => unreachable!("Invalid variant for AutomixStyle: {}", inner),
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::engine::DeviceProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_cores = <u32>::sse_decode(deserializer);
        let mut var_avx2 = <bool>::sse_decode(deserializer);
        let mut var_recommendedModel = <String>::sse_decode(deserializer);
        let mut var_fullModelDownloaded = <bool>::sse_decode(deserializer);
        let mut var_activeModel = <String>::sse_decode(deserializer);
        return crate::api::engine::DeviceProfile {
            cores: var_cores,
            avx2: var_avx2,
            recommended_model: var_recommendedModel,
            full_model_downloaded: var_fullModelDownloaded,
            active_model: var_activeModel,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::engine::OutputDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::engine::OutputDevice>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::engine::MediaAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::engine::MediaAction::Play;
            }
            1 => {
                return crate::api::engine::MediaAction::Pause;
            }
            2 => {
                return crate::api::engine::MediaAction::Toggle;
            }
            3 => {
                return crate::api::engine::MediaAction::Next;
            }
            4 => {
                return crate::api::engine::MediaAction::Previous;
            }
            5 => {
                return crate::api::engine::MediaAction::Stop;
            }
            6 => {
                let mut var_positionMs = <i64>::sse_decode(deserializer);
                return crate::api::engine::MediaAction::SeekTo {
                    position_ms: var_positionMs,
                };
            }
            7 => {
                let mut var_deltaMs = <i64>::sse_decode(deserializer);
                return crate::api::engine::MediaAction::SeekBy {
                    delta_ms: var_deltaMs,
                };
            }
            8 => {
                let mut var_volume = <f64>::sse_decode(deserializer);
                return crate::api::engine::MediaAction::SetVolume { volume: var_volume };
            }
            9 => {
                return crate::api::engine::MediaAction::Raise;
            }
            10 => {
                return crate::api::engine::MediaAction::Quit;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::engine::TrackSource> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::engine::TrackSource>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::engine::OutputDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_isDefault = <bool>::sse_decode(deserializer);
        return crate::api::engine::OutputDevice {
            id: var_id,
            name: var_name,
            is_default: var_isDefault,
        };
    }
}

impl SseDecode for crate::api::engine::PlayerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_cacheDir = <String>::sse_decode(deserializer);
        let mut var_cacheLimitMb = <u32>::sse_decode(deserializer);
        let mut var_deviceId = <Option<String>>::sse_decode(deserializer);
        let mut var_appId = <String>::sse_decode(deserializer);
        let mut var_appName = <String>::sse_decode(deserializer);
        let mut var_mediaControls = <bool>::sse_decode(deserializer);
        let mut var_modelDir = <Option<String>>::sse_decode(deserializer);
        let mut var_analysisModel = <String>::sse_decode(deserializer);
        return crate::api::engine::PlayerConfig {
            cache_dir: var_cacheDir,
            cache_limit_mb: var_cacheLimitMb,
            device_id: var_deviceId,
            app_id: var_appId,
            app_name: var_appName,
            media_controls: var_mediaControls,
            model_dir: var_modelDir,
            analysis_model: var_analysisModel,
        };
    }
}

impl SseDecode for crate::api::engine::PlayerEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::TrackStarted { id: var_id };
            }
            1 => {
                let mut var_id = <String>::sse_decode(deserializer);
                let mut var_error = <Option<String>>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::TrackEnded {
                    id: var_id,
                    error: var_error,
                };
            }
            2 => {
                let mut var_id = <String>::sse_decode(deserializer);
                let mut var_positionMs = <i64>::sse_decode(deserializer);
                let mut var_durationMs = <Option<i64>>::sse_decode(deserializer);
                let mut var_buffered = <Option<f32>>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::Position {
                    id: var_id,
                    position_ms: var_positionMs,
                    duration_ms: var_durationMs,
                    buffered: var_buffered,
                };
            }
            3 => {
                let mut var_playing = <bool>::sse_decode(deserializer);
                let mut var_buffering = <bool>::sse_decode(deserializer);
                let mut var_hasTrack = <bool>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::State {
                    playing: var_playing,
                    buffering: var_buffering,
                    has_track: var_hasTrack,
                };
            }
            4 => {
                let mut var_action = <crate::api::engine::MediaAction>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::MediaControl { action: var_action };
            }
            5 => {
                let mut var_name = <String>::sse_decode(deserializer);
                let mut var_sampleRate = <u32>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::DeviceChanged {
                    name: var_name,
                    sample_rate: var_sampleRate,
                };
            }
            6 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::Error {
                    message: var_message,
                };
            }
            7 => {
                let mut var_id = <String>::sse_decode(deserializer);
                let mut var_bpm = <Option<f64>>::sse_decode(deserializer);
                let mut var_key = <Option<String>>::sse_decode(deserializer);
                let mut var_camelot = <Option<String>>::sse_decode(deserializer);
                let mut var_reliable = <bool>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::Analysis {
                    id: var_id,
                    bpm: var_bpm,
                    key: var_key,
                    camelot: var_camelot,
                    reliable: var_reliable,
                };
            }
            8 => {
                let mut var_fromId = <String>::sse_decode(deserializer);
                let mut var_toId = <String>::sse_decode(deserializer);
                let mut var_summary = <String>::sse_decode(deserializer);
                let mut var_beatmatched = <bool>::sse_decode(deserializer);
                let mut var_startsInMs = <i64>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::MixPlanned {
                    from_id: var_fromId,
                    to_id: var_toId,
                    summary: var_summary,
                    beatmatched: var_beatmatched,
                    starts_in_ms: var_startsInMs,
                };
            }
            9 => {
                let mut var_fromId = <String>::sse_decode(deserializer);
                let mut var_toId = <String>::sse_decode(deserializer);
                let mut var_summary = <String>::sse_decode(deserializer);
                let mut var_style = <String>::sse_decode(deserializer);
                let mut var_durationMs = <i64>::sse_decode(deserializer);
                return crate::api::engine::PlayerEvent::MixStarted {
                    from_id: var_fromId,
                    to_id: var_toId,
                    summary: var_summary,
                    style: var_style,
                    duration_ms: var_durationMs,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::engine::TrackSource {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_cacheKey = <Option<String>>::sse_decode(deserializer);
        let mut var_formatHint = <Option<String>>::sse_decode(deserializer);
        let mut var_durationMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_gainDb = <f32>::sse_decode(deserializer);
        let mut var_peak = <Option<f32>>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_artist = <String>::sse_decode(deserializer);
        let mut var_album = <String>::sse_decode(deserializer);
        let mut var_coverUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_coverKey = <Option<String>>::sse_decode(deserializer);
        let mut var_analysisKey = <Option<String>>::sse_decode(deserializer);
        return crate::api::engine::TrackSource {
            id: var_id,
            url: var_url,
            cache_key: var_cacheKey,
            format_hint: var_formatHint,
            duration_ms: var_durationMs,
            gain_db: var_gainDb,
            peak: var_peak,
            title: var_title,
            artist: var_artist,
            album: var_album,
            cover_url: var_coverUrl,
            cover_key: var_coverKey,
            analysis_key: var_analysisKey,
        };
    }
}

impl SseDecode for crate::api::engine::TransitionMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::engine::TransitionMode::Gapless;
            }
            1 => {
                let mut var_ms = <u32>::sse_decode(deserializer);
                return crate::api::engine::TransitionMode::Crossfade { ms: var_ms };
            }
            2 => {
                return crate::api::engine::TransitionMode::Cut;
            }
            3 => {
                return crate::api::engine::TransitionMode::Automix;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__engine__init_app_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__engine__player_analyze_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__engine__player_cache_size_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__engine__player_clear_cache_impl(port, ptr, rust_vec_len, data_len),
        5 => {
            wire__crate__api__engine__player_device_profile_impl(port, ptr, rust_vec_len, data_len)
        }
        6 => wire__crate__api__engine__player_download_full_model_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__engine__player_events_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__engine__player_init_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__engine__player_is_cached_impl(port, ptr, rust_vec_len, data_len),
        11 => {
            wire__crate__api__engine__player_output_devices_impl(port, ptr, rust_vec_len, data_len)
        }
        14 => wire__crate__api__engine__player_prefetch_impl(port, ptr, rust_vec_len, data_len),
        18 => wire__crate__api__engine__player_set_analysis_model_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        20 => {
            wire__crate__api__engine__player_set_cache_limit_impl(port, ptr, rust_vec_len, data_len)
        }
        23 => wire__crate__api__engine__player_set_output_device_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        10 => wire__crate__api__engine__player_model_download_progress_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        12 => wire__crate__api__engine__player_pause_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__engine__player_play_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__engine__player_resume_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__engine__player_seek_impl(ptr, rust_vec_len, data_len),
        17 => wire__crate__api__engine__player_seek_by_impl(ptr, rust_vec_len, data_len),
        19 => wire__crate__api__engine__player_set_automix_impl(ptr, rust_vec_len, data_len),
        21 => wire__crate__api__engine__player_set_next_impl(ptr, rust_vec_len, data_len),
        22 => wire__crate__api__engine__player_set_notifications_impl(ptr, rust_vec_len, data_len),
        24 => wire__crate__api__engine__player_set_volume_impl(ptr, rust_vec_len, data_len),
        25 => wire__crate__api__engine__player_stop_impl(ptr, rust_vec_len, data_len),
        26 => wire__crate__api__engine__player_toggle_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::AutomixConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.style.into_into_dart().into_dart(),
            self.max_tempo_change.into_into_dart().into_dart(),
            self.preferred_bars.into_into_dart().into_dart(),
            self.min_bars.into_into_dart().into_dart(),
            self.max_seconds.into_into_dart().into_dart(),
            self.unclear_seconds.into_into_dart().into_dart(),
            self.harmonic.into_into_dart().into_dart(),
            self.tempo_ramp_bars.into_into_dart().into_dart(),
            self.trim_silence.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::AutomixConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::AutomixConfig>
    for crate::api::engine::AutomixConfig
{
    fn into_into_dart(self) -> crate::api::engine::AutomixConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::AutomixStyle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Auto => 0.into_dart(),
            Self::BassSwap => 1.into_dart(),
            Self::Blend => 2.into_dart(),
            Self::Filter => 3.into_dart(),
            Self::Echo => 4.into_dart(),
            Self::Cut => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::AutomixStyle
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::AutomixStyle>
    for crate::api::engine::AutomixStyle
{
    fn into_into_dart(self) -> crate::api::engine::AutomixStyle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::DeviceProfile {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.cores.into_into_dart().into_dart(),
            self.avx2.into_into_dart().into_dart(),
            self.recommended_model.into_into_dart().into_dart(),
            self.full_model_downloaded.into_into_dart().into_dart(),
            self.active_model.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::DeviceProfile
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::DeviceProfile>
    for crate::api::engine::DeviceProfile
{
    fn into_into_dart(self) -> crate::api::engine::DeviceProfile {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::MediaAction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::engine::MediaAction::Play => [0.into_dart()].into_dart(),
            crate::api::engine::MediaAction::Pause => [1.into_dart()].into_dart(),
            crate::api::engine::MediaAction::Toggle => [2.into_dart()].into_dart(),
            crate::api::engine::MediaAction::Next => [3.into_dart()].into_dart(),
            crate::api::engine::MediaAction::Previous => [4.into_dart()].into_dart(),
            crate::api::engine::MediaAction::Stop => [5.into_dart()].into_dart(),
            crate::api::engine::MediaAction::SeekTo { position_ms } => {
                [6.into_dart(), position_ms.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::MediaAction::SeekBy { delta_ms } => {
                [7.into_dart(), delta_ms.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::MediaAction::SetVolume { volume } => {
                [8.into_dart(), volume.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::MediaAction::Raise => [9.into_dart()].into_dart(),
            crate::api::engine::MediaAction::Quit => [10.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::MediaAction
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::MediaAction>
    for crate::api::engine::MediaAction
{
    fn into_into_dart(self) -> crate::api::engine::MediaAction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::OutputDevice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.is_default.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::OutputDevice
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::OutputDevice>
    for crate::api::engine::OutputDevice
{
    fn into_into_dart(self) -> crate::api::engine::OutputDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::PlayerConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.cache_dir.into_into_dart().into_dart(),
            self.cache_limit_mb.into_into_dart().into_dart(),
            self.device_id.into_into_dart().into_dart(),
            self.app_id.into_into_dart().into_dart(),
            self.app_name.into_into_dart().into_dart(),
            self.media_controls.into_into_dart().into_dart(),
            self.model_dir.into_into_dart().into_dart(),
            self.analysis_model.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::PlayerConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::PlayerConfig>
    for crate::api::engine::PlayerConfig
{
    fn into_into_dart(self) -> crate::api::engine::PlayerConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::PlayerEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::engine::PlayerEvent::TrackStarted { id } => {
                [0.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::PlayerEvent::TrackEnded { id, error } => [
                1.into_dart(),
                id.into_into_dart().into_dart(),
                error.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::engine::PlayerEvent::Position {
                id,
                position_ms,
                duration_ms,
                buffered,
            } => [
                2.into_dart(),
                id.into_into_dart().into_dart(),
                position_ms.into_into_dart().into_dart(),
                duration_ms.into_into_dart().into_dart(),
                buffered.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::engine::PlayerEvent::State {
                playing,
                buffering,
                has_track,
            } => [
                3.into_dart(),
                playing.into_into_dart().into_dart(),
                buffering.into_into_dart().into_dart(),
                has_track.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::engine::PlayerEvent::MediaControl { action } => {
                [4.into_dart(), action.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::PlayerEvent::DeviceChanged { name, sample_rate } => [
                5.into_dart(),
                name.into_into_dart().into_dart(),
                sample_rate.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::engine::PlayerEvent::Error { message } => {
                [6.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::PlayerEvent::Analysis {
                id,
                bpm,
                key,
                camelot,
                reliable,
            } => [
                7.into_dart(),
                id.into_into_dart().into_dart(),
                bpm.into_into_dart().into_dart(),
                key.into_into_dart().into_dart(),
                camelot.into_into_dart().into_dart(),
                reliable.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::engine::PlayerEvent::MixPlanned {
                from_id,
                to_id,
                summary,
                beatmatched,
                starts_in_ms,
            } => [
                8.into_dart(),
                from_id.into_into_dart().into_dart(),
                to_id.into_into_dart().into_dart(),
                summary.into_into_dart().into_dart(),
                beatmatched.into_into_dart().into_dart(),
                starts_in_ms.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::engine::PlayerEvent::MixStarted {
                from_id,
                to_id,
                summary,
                style,
                duration_ms,
            } => [
                9.into_dart(),
                from_id.into_into_dart().into_dart(),
                to_id.into_into_dart().into_dart(),
                summary.into_into_dart().into_dart(),
                style.into_into_dart().into_dart(),
                duration_ms.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::PlayerEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::PlayerEvent>
    for crate::api::engine::PlayerEvent
{
    fn into_into_dart(self) -> crate::api::engine::PlayerEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::TrackSource {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.cache_key.into_into_dart().into_dart(),
            self.format_hint.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.gain_db.into_into_dart().into_dart(),
            self.peak.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.artist.into_into_dart().into_dart(),
            self.album.into_into_dart().into_dart(),
            self.cover_url.into_into_dart().into_dart(),
            self.cover_key.into_into_dart().into_dart(),
            self.analysis_key.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::TrackSource
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::TrackSource>
    for crate::api::engine::TrackSource
{
    fn into_into_dart(self) -> crate::api::engine::TrackSource {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::TransitionMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::engine::TransitionMode::Gapless => [0.into_dart()].into_dart(),
            crate::api::engine::TransitionMode::Crossfade { ms } => {
                [1.into_dart(), ms.into_into_dart().into_dart()].into_dart()
            }
            crate::api::engine::TransitionMode::Cut => [2.into_dart()].into_dart(),
            crate::api::engine::TransitionMode::Automix => [3.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::TransitionMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::TransitionMode>
    for crate::api::engine::TransitionMode
{
    fn into_into_dart(self) -> crate::api::engine::TransitionMode {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::engine::PlayerEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::engine::AutomixConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::engine::AutomixStyle>::sse_encode(self.style, serializer);
        <f64>::sse_encode(self.max_tempo_change, serializer);
        <u32>::sse_encode(self.preferred_bars, serializer);
        <u32>::sse_encode(self.min_bars, serializer);
        <f64>::sse_encode(self.max_seconds, serializer);
        <f64>::sse_encode(self.unclear_seconds, serializer);
        <bool>::sse_encode(self.harmonic, serializer);
        <u32>::sse_encode(self.tempo_ramp_bars, serializer);
        <bool>::sse_encode(self.trim_silence, serializer);
    }
}

impl SseEncode for crate::api::engine::AutomixStyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::engine::AutomixStyle::Auto => 0,
                crate::api::engine::AutomixStyle::BassSwap => 1,
                crate::api::engine::AutomixStyle::Blend => 2,
                crate::api::engine::AutomixStyle::Filter => 3,
                crate::api::engine::AutomixStyle::Echo => 4,
                crate::api::engine::AutomixStyle::Cut => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::engine::DeviceProfile {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.cores, serializer);
        <bool>::sse_encode(self.avx2, serializer);
        <String>::sse_encode(self.recommended_model, serializer);
        <bool>::sse_encode(self.full_model_downloaded, serializer);
        <String>::sse_encode(self.active_model, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::engine::OutputDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::engine::OutputDevice>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::engine::MediaAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::engine::MediaAction::Play => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::engine::MediaAction::Pause => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::engine::MediaAction::Toggle => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::engine::MediaAction::Next => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::engine::MediaAction::Previous => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::engine::MediaAction::Stop => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::engine::MediaAction::SeekTo { position_ms } => {
                <i32>::sse_encode(6, serializer);
                <i64>::sse_encode(position_ms, serializer);
            }
            crate::api::engine::MediaAction::SeekBy { delta_ms } => {
                <i32>::sse_encode(7, serializer);
                <i64>::sse_encode(delta_ms, serializer);
            }
            crate::api::engine::MediaAction::SetVolume { volume } => {
                <i32>::sse_encode(8, serializer);
                <f64>::sse_encode(volume, serializer);
            }
            crate::api::engine::MediaAction::Raise => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::engine::MediaAction::Quit => {
                <i32>::sse_encode(10, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::engine::TrackSource> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::engine::TrackSource>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::engine::OutputDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <bool>::sse_encode(self.is_default, serializer);
    }
}

impl SseEncode for crate::api::engine::PlayerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.cache_dir, serializer);
        <u32>::sse_encode(self.cache_limit_mb, serializer);
        <Option<String>>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.app_id, serializer);
        <String>::sse_encode(self.app_name, serializer);
        <bool>::sse_encode(self.media_controls, serializer);
        <Option<String>>::sse_encode(self.model_dir, serializer);
        <String>::sse_encode(self.analysis_model, serializer);
    }
}

impl SseEncode for crate::api::engine::PlayerEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::engine::PlayerEvent::TrackStarted { id } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::engine::PlayerEvent::TrackEnded { id, error } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(id, serializer);
                <Option<String>>::sse_encode(error, serializer);
            }
            crate::api::engine::PlayerEvent::Position {
                id,
                position_ms,
                duration_ms,
                buffered,
            } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(id, serializer);
                <i64>::sse_encode(position_ms, serializer);
                <Option<i64>>::sse_encode(duration_ms, serializer);
                <Option<f32>>::sse_encode(buffered, serializer);
            }
            crate::api::engine::PlayerEvent::State {
                playing,
                buffering,
                has_track,
            } => {
                <i32>::sse_encode(3, serializer);
                <bool>::sse_encode(playing, serializer);
                <bool>::sse_encode(buffering, serializer);
                <bool>::sse_encode(has_track, serializer);
            }
            crate::api::engine::PlayerEvent::MediaControl { action } => {
                <i32>::sse_encode(4, serializer);
                <crate::api::engine::MediaAction>::sse_encode(action, serializer);
            }
            crate::api::engine::PlayerEvent::DeviceChanged { name, sample_rate } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(name, serializer);
                <u32>::sse_encode(sample_rate, serializer);
            }
            crate::api::engine::PlayerEvent::Error { message } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::engine::PlayerEvent::Analysis {
                id,
                bpm,
                key,
                camelot,
                reliable,
            } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(id, serializer);
                <Option<f64>>::sse_encode(bpm, serializer);
                <Option<String>>::sse_encode(key, serializer);
                <Option<String>>::sse_encode(camelot, serializer);
                <bool>::sse_encode(reliable, serializer);
            }
            crate::api::engine::PlayerEvent::MixPlanned {
                from_id,
                to_id,
                summary,
                beatmatched,
                starts_in_ms,
            } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(from_id, serializer);
                <String>::sse_encode(to_id, serializer);
                <String>::sse_encode(summary, serializer);
                <bool>::sse_encode(beatmatched, serializer);
                <i64>::sse_encode(starts_in_ms, serializer);
            }
            crate::api::engine::PlayerEvent::MixStarted {
                from_id,
                to_id,
                summary,
                style,
                duration_ms,
            } => {
                <i32>::sse_encode(9, serializer);
                <String>::sse_encode(from_id, serializer);
                <String>::sse_encode(to_id, serializer);
                <String>::sse_encode(summary, serializer);
                <String>::sse_encode(style, serializer);
                <i64>::sse_encode(duration_ms, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::engine::TrackSource {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.url, serializer);
        <Option<String>>::sse_encode(self.cache_key, serializer);
        <Option<String>>::sse_encode(self.format_hint, serializer);
        <Option<i64>>::sse_encode(self.duration_ms, serializer);
        <f32>::sse_encode(self.gain_db, serializer);
        <Option<f32>>::sse_encode(self.peak, serializer);
        <String>::sse_encode(self.title, serializer);
        <String>::sse_encode(self.artist, serializer);
        <String>::sse_encode(self.album, serializer);
        <Option<String>>::sse_encode(self.cover_url, serializer);
        <Option<String>>::sse_encode(self.cover_key, serializer);
        <Option<String>>::sse_encode(self.analysis_key, serializer);
    }
}

impl SseEncode for crate::api::engine::TransitionMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::engine::TransitionMode::Gapless => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::engine::TransitionMode::Crossfade { ms } => {
                <i32>::sse_encode(1, serializer);
                <u32>::sse_encode(ms, serializer);
            }
            crate::api::engine::TransitionMode::Cut => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::engine::TransitionMode::Automix => {
                <i32>::sse_encode(3, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
