// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/library.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<PlayerEvent> dco_decode_StreamSink_player_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AutomixConfig dco_decode_automix_config(dynamic raw);

  @protected
  AutomixStyle dco_decode_automix_style(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AutomixConfig dco_decode_box_autoadd_automix_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LocalTrack dco_decode_box_autoadd_local_track(dynamic raw);

  @protected
  MediaAction dco_decode_box_autoadd_media_action(dynamic raw);

  @protected
  PlayerConfig dco_decode_box_autoadd_player_config(dynamic raw);

  @protected
  TrackSource dco_decode_box_autoadd_track_source(dynamic raw);

  @protected
  TransitionMode dco_decode_box_autoadd_transition_mode(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DeviceProfile dco_decode_device_profile(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<LocalTrack> dco_decode_list_local_track(dynamic raw);

  @protected
  List<OfflineItem> dco_decode_list_offline_item(dynamic raw);

  @protected
  List<OfflineTrack> dco_decode_list_offline_track(dynamic raw);

  @protected
  List<OutputDevice> dco_decode_list_output_device(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LocalTrack dco_decode_local_track(dynamic raw);

  @protected
  MediaAction dco_decode_media_action(dynamic raw);

  @protected
  OfflineItem dco_decode_offline_item(dynamic raw);

  @protected
  OfflineItemState dco_decode_offline_item_state(dynamic raw);

  @protected
  OfflineStatus dco_decode_offline_status(dynamic raw);

  @protected
  OfflineTrack dco_decode_offline_track(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LocalTrack? dco_decode_opt_box_autoadd_local_track(dynamic raw);

  @protected
  TrackSource? dco_decode_opt_box_autoadd_track_source(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  OutputDevice dco_decode_output_device(dynamic raw);

  @protected
  PlayerConfig dco_decode_player_config(dynamic raw);

  @protected
  PlayerEvent dco_decode_player_event(dynamic raw);

  @protected
  TrackSource dco_decode_track_source(dynamic raw);

  @protected
  TransitionMode dco_decode_transition_mode(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<PlayerEvent> sse_decode_StreamSink_player_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AutomixConfig sse_decode_automix_config(SseDeserializer deserializer);

  @protected
  AutomixStyle sse_decode_automix_style(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AutomixConfig sse_decode_box_autoadd_automix_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LocalTrack sse_decode_box_autoadd_local_track(SseDeserializer deserializer);

  @protected
  MediaAction sse_decode_box_autoadd_media_action(SseDeserializer deserializer);

  @protected
  PlayerConfig sse_decode_box_autoadd_player_config(
    SseDeserializer deserializer,
  );

  @protected
  TrackSource sse_decode_box_autoadd_track_source(SseDeserializer deserializer);

  @protected
  TransitionMode sse_decode_box_autoadd_transition_mode(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DeviceProfile sse_decode_device_profile(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<LocalTrack> sse_decode_list_local_track(SseDeserializer deserializer);

  @protected
  List<OfflineItem> sse_decode_list_offline_item(SseDeserializer deserializer);

  @protected
  List<OfflineTrack> sse_decode_list_offline_track(
    SseDeserializer deserializer,
  );

  @protected
  List<OutputDevice> sse_decode_list_output_device(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LocalTrack sse_decode_local_track(SseDeserializer deserializer);

  @protected
  MediaAction sse_decode_media_action(SseDeserializer deserializer);

  @protected
  OfflineItem sse_decode_offline_item(SseDeserializer deserializer);

  @protected
  OfflineItemState sse_decode_offline_item_state(SseDeserializer deserializer);

  @protected
  OfflineStatus sse_decode_offline_status(SseDeserializer deserializer);

  @protected
  OfflineTrack sse_decode_offline_track(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LocalTrack? sse_decode_opt_box_autoadd_local_track(
    SseDeserializer deserializer,
  );

  @protected
  TrackSource? sse_decode_opt_box_autoadd_track_source(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  OutputDevice sse_decode_output_device(SseDeserializer deserializer);

  @protected
  PlayerConfig sse_decode_player_config(SseDeserializer deserializer);

  @protected
  PlayerEvent sse_decode_player_event(SseDeserializer deserializer);

  @protected
  TrackSource sse_decode_track_source(SseDeserializer deserializer);

  @protected
  TransitionMode sse_decode_transition_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_player_event_Sse(
    RustStreamSink<PlayerEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_automix_config(AutomixConfig self, SseSerializer serializer);

  @protected
  void sse_encode_automix_style(AutomixStyle self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_automix_config(
    AutomixConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_track(
    LocalTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_action(
    MediaAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_player_config(
    PlayerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_source(
    TrackSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transition_mode(
    TransitionMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_device_profile(DeviceProfile self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_local_track(
    List<LocalTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_offline_item(
    List<OfflineItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_offline_track(
    List<OfflineTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_output_device(
    List<OutputDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_track(LocalTrack self, SseSerializer serializer);

  @protected
  void sse_encode_media_action(MediaAction self, SseSerializer serializer);

  @protected
  void sse_encode_offline_item(OfflineItem self, SseSerializer serializer);

  @protected
  void sse_encode_offline_item_state(
    OfflineItemState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_offline_status(OfflineStatus self, SseSerializer serializer);

  @protected
  void sse_encode_offline_track(OfflineTrack self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_local_track(
    LocalTrack? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_track_source(
    TrackSource? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_output_device(OutputDevice self, SseSerializer serializer);

  @protected
  void sse_encode_player_config(PlayerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_player_event(PlayerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_track_source(TrackSource self, SseSerializer serializer);

  @protected
  void sse_encode_transition_mode(
    TransitionMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
