// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEngineInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1833760042;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'player_engine',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiEngineInitApp();

  Future<PlatformInt64> crateApiEnginePlayerCacheSize();

  Future<void> crateApiEnginePlayerClearCache();

  Stream<PlayerEvent> crateApiEnginePlayerEvents();

  Future<void> crateApiEnginePlayerInit({required PlayerConfig config});

  Future<bool> crateApiEnginePlayerIsCached({required String cacheKey});

  Future<List<OutputDevice>> crateApiEnginePlayerOutputDevices();

  void crateApiEnginePlayerPause();

  void crateApiEnginePlayerPlay({
    required TrackSource track,
    required PlatformInt64 startMs,
  });

  Future<void> crateApiEnginePlayerPrefetch({required TrackSource track});

  void crateApiEnginePlayerResume();

  void crateApiEnginePlayerSeek({required PlatformInt64 positionMs});

  void crateApiEnginePlayerSeekBy({required PlatformInt64 deltaMs});

  Future<void> crateApiEnginePlayerSetCacheLimit({required int limitMb});

  void crateApiEnginePlayerSetNext({
    TrackSource? track,
    required TransitionMode mode,
  });

  void crateApiEnginePlayerSetNotifications({required bool enabled});

  Future<void> crateApiEnginePlayerSetOutputDevice({String? deviceId});

  void crateApiEnginePlayerSetVolume({required double volume});

  void crateApiEnginePlayerStop();

  void crateApiEnginePlayerToggle();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiEngineInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<PlatformInt64> crateApiEnginePlayerCacheSize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerCacheSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerCacheSizeConstMeta =>
      const TaskConstMeta(debugName: "player_cache_size", argNames: []);

  @override
  Future<void> crateApiEnginePlayerClearCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerClearCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerClearCacheConstMeta =>
      const TaskConstMeta(debugName: "player_clear_cache", argNames: []);

  @override
  Stream<PlayerEvent> crateApiEnginePlayerEvents() {
    final sink = RustStreamSink<PlayerEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_player_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEnginePlayerEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEnginePlayerEventsConstMeta =>
      const TaskConstMeta(debugName: "player_events", argNames: ["sink"]);

  @override
  Future<void> crateApiEnginePlayerInit({required PlayerConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_player_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerInitConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerInitConstMeta =>
      const TaskConstMeta(debugName: "player_init", argNames: ["config"]);

  @override
  Future<bool> crateApiEnginePlayerIsCached({required String cacheKey}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cacheKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerIsCachedConstMeta,
        argValues: [cacheKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerIsCachedConstMeta =>
      const TaskConstMeta(
        debugName: "player_is_cached",
        argNames: ["cacheKey"],
      );

  @override
  Future<List<OutputDevice>> crateApiEnginePlayerOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_output_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "player_output_devices", argNames: []);

  @override
  void crateApiEnginePlayerPause() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "player_pause", argNames: []);

  @override
  void crateApiEnginePlayerPlay({
    required TrackSource track,
    required PlatformInt64 startMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_track_source(track, serializer);
          sse_encode_i_64(startMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerPlayConstMeta,
        argValues: [track, startMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerPlayConstMeta => const TaskConstMeta(
    debugName: "player_play",
    argNames: ["track", "startMs"],
  );

  @override
  Future<void> crateApiEnginePlayerPrefetch({required TrackSource track}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_track_source(track, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerPrefetchConstMeta,
        argValues: [track],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerPrefetchConstMeta =>
      const TaskConstMeta(debugName: "player_prefetch", argNames: ["track"]);

  @override
  void crateApiEnginePlayerResume() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerResumeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerResumeConstMeta =>
      const TaskConstMeta(debugName: "player_resume", argNames: []);

  @override
  void crateApiEnginePlayerSeek({required PlatformInt64 positionMs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(positionMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSeekConstMeta,
        argValues: [positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSeekConstMeta =>
      const TaskConstMeta(debugName: "player_seek", argNames: ["positionMs"]);

  @override
  void crateApiEnginePlayerSeekBy({required PlatformInt64 deltaMs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(deltaMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSeekByConstMeta,
        argValues: [deltaMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSeekByConstMeta =>
      const TaskConstMeta(debugName: "player_seek_by", argNames: ["deltaMs"]);

  @override
  Future<void> crateApiEnginePlayerSetCacheLimit({required int limitMb}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limitMb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSetCacheLimitConstMeta,
        argValues: [limitMb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSetCacheLimitConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_cache_limit",
        argNames: ["limitMb"],
      );

  @override
  void crateApiEnginePlayerSetNext({
    TrackSource? track,
    required TransitionMode mode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_track_source(track, serializer);
          sse_encode_box_autoadd_transition_mode(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSetNextConstMeta,
        argValues: [track, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSetNextConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_next",
        argNames: ["track", "mode"],
      );

  @override
  void crateApiEnginePlayerSetNotifications({required bool enabled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSetNotificationsConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSetNotificationsConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_notifications",
        argNames: ["enabled"],
      );

  @override
  Future<void> crateApiEnginePlayerSetOutputDevice({String? deviceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSetOutputDeviceConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSetOutputDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_output_device",
        argNames: ["deviceId"],
      );

  @override
  void crateApiEnginePlayerSetVolume({required double volume}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(volume, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerSetVolumeConstMeta,
        argValues: [volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerSetVolumeConstMeta =>
      const TaskConstMeta(debugName: "player_set_volume", argNames: ["volume"]);

  @override
  void crateApiEnginePlayerStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerStopConstMeta =>
      const TaskConstMeta(debugName: "player_stop", argNames: []);

  @override
  void crateApiEnginePlayerToggle() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePlayerToggleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePlayerToggleConstMeta =>
      const TaskConstMeta(debugName: "player_toggle", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<PlayerEvent> dco_decode_StreamSink_player_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MediaAction dco_decode_box_autoadd_media_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_action(raw);
  }

  @protected
  PlayerConfig dco_decode_box_autoadd_player_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_player_config(raw);
  }

  @protected
  TrackSource dco_decode_box_autoadd_track_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_track_source(raw);
  }

  @protected
  TransitionMode dco_decode_box_autoadd_transition_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transition_mode(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<OutputDevice> dco_decode_list_output_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_output_device).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaAction dco_decode_media_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MediaAction_Play();
      case 1:
        return MediaAction_Pause();
      case 2:
        return MediaAction_Toggle();
      case 3:
        return MediaAction_Next();
      case 4:
        return MediaAction_Previous();
      case 5:
        return MediaAction_Stop();
      case 6:
        return MediaAction_SeekTo(positionMs: dco_decode_i_64(raw[1]));
      case 7:
        return MediaAction_SeekBy(deltaMs: dco_decode_i_64(raw[1]));
      case 8:
        return MediaAction_SetVolume(volume: dco_decode_f_64(raw[1]));
      case 9:
        return MediaAction_Raise();
      case 10:
        return MediaAction_Quit();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  TrackSource? dco_decode_opt_box_autoadd_track_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_track_source(raw);
  }

  @protected
  OutputDevice dco_decode_output_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OutputDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isDefault: dco_decode_bool(arr[2]),
    );
  }

  @protected
  PlayerConfig dco_decode_player_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PlayerConfig(
      cacheDir: dco_decode_String(arr[0]),
      cacheLimitMb: dco_decode_u_32(arr[1]),
      deviceId: dco_decode_opt_String(arr[2]),
      appId: dco_decode_String(arr[3]),
      appName: dco_decode_String(arr[4]),
      mediaControls: dco_decode_bool(arr[5]),
    );
  }

  @protected
  PlayerEvent dco_decode_player_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PlayerEvent_TrackStarted(id: dco_decode_String(raw[1]));
      case 1:
        return PlayerEvent_TrackEnded(
          id: dco_decode_String(raw[1]),
          error: dco_decode_opt_String(raw[2]),
        );
      case 2:
        return PlayerEvent_Position(
          id: dco_decode_String(raw[1]),
          positionMs: dco_decode_i_64(raw[2]),
          durationMs: dco_decode_opt_box_autoadd_i_64(raw[3]),
          buffered: dco_decode_opt_box_autoadd_f_32(raw[4]),
        );
      case 3:
        return PlayerEvent_State(
          playing: dco_decode_bool(raw[1]),
          buffering: dco_decode_bool(raw[2]),
          hasTrack: dco_decode_bool(raw[3]),
        );
      case 4:
        return PlayerEvent_MediaControl(
          action: dco_decode_box_autoadd_media_action(raw[1]),
        );
      case 5:
        return PlayerEvent_DeviceChanged(
          name: dco_decode_String(raw[1]),
          sampleRate: dco_decode_u_32(raw[2]),
        );
      case 6:
        return PlayerEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TrackSource dco_decode_track_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return TrackSource(
      id: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      cacheKey: dco_decode_opt_String(arr[2]),
      formatHint: dco_decode_opt_String(arr[3]),
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[4]),
      gainDb: dco_decode_f_32(arr[5]),
      peak: dco_decode_opt_box_autoadd_f_32(arr[6]),
      title: dco_decode_String(arr[7]),
      artist: dco_decode_String(arr[8]),
      album: dco_decode_String(arr[9]),
      coverUrl: dco_decode_opt_String(arr[10]),
      coverKey: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  TransitionMode dco_decode_transition_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TransitionMode_Gapless();
      case 1:
        return TransitionMode_Crossfade(ms: dco_decode_u_32(raw[1]));
      case 2:
        return TransitionMode_Cut();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<PlayerEvent> sse_decode_StreamSink_player_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MediaAction sse_decode_box_autoadd_media_action(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_action(deserializer));
  }

  @protected
  PlayerConfig sse_decode_box_autoadd_player_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_player_config(deserializer));
  }

  @protected
  TrackSource sse_decode_box_autoadd_track_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_track_source(deserializer));
  }

  @protected
  TransitionMode sse_decode_box_autoadd_transition_mode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transition_mode(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<OutputDevice> sse_decode_list_output_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OutputDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_output_device(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaAction sse_decode_media_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return MediaAction_Play();
      case 1:
        return MediaAction_Pause();
      case 2:
        return MediaAction_Toggle();
      case 3:
        return MediaAction_Next();
      case 4:
        return MediaAction_Previous();
      case 5:
        return MediaAction_Stop();
      case 6:
        var var_positionMs = sse_decode_i_64(deserializer);
        return MediaAction_SeekTo(positionMs: var_positionMs);
      case 7:
        var var_deltaMs = sse_decode_i_64(deserializer);
        return MediaAction_SeekBy(deltaMs: var_deltaMs);
      case 8:
        var var_volume = sse_decode_f_64(deserializer);
        return MediaAction_SetVolume(volume: var_volume);
      case 9:
        return MediaAction_Raise();
      case 10:
        return MediaAction_Quit();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TrackSource? sse_decode_opt_box_autoadd_track_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_track_source(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OutputDevice sse_decode_output_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isDefault = sse_decode_bool(deserializer);
    return OutputDevice(id: var_id, name: var_name, isDefault: var_isDefault);
  }

  @protected
  PlayerConfig sse_decode_player_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cacheDir = sse_decode_String(deserializer);
    var var_cacheLimitMb = sse_decode_u_32(deserializer);
    var var_deviceId = sse_decode_opt_String(deserializer);
    var var_appId = sse_decode_String(deserializer);
    var var_appName = sse_decode_String(deserializer);
    var var_mediaControls = sse_decode_bool(deserializer);
    return PlayerConfig(
      cacheDir: var_cacheDir,
      cacheLimitMb: var_cacheLimitMb,
      deviceId: var_deviceId,
      appId: var_appId,
      appName: var_appName,
      mediaControls: var_mediaControls,
    );
  }

  @protected
  PlayerEvent sse_decode_player_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_id = sse_decode_String(deserializer);
        return PlayerEvent_TrackStarted(id: var_id);
      case 1:
        var var_id = sse_decode_String(deserializer);
        var var_error = sse_decode_opt_String(deserializer);
        return PlayerEvent_TrackEnded(id: var_id, error: var_error);
      case 2:
        var var_id = sse_decode_String(deserializer);
        var var_positionMs = sse_decode_i_64(deserializer);
        var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
        var var_buffered = sse_decode_opt_box_autoadd_f_32(deserializer);
        return PlayerEvent_Position(
          id: var_id,
          positionMs: var_positionMs,
          durationMs: var_durationMs,
          buffered: var_buffered,
        );
      case 3:
        var var_playing = sse_decode_bool(deserializer);
        var var_buffering = sse_decode_bool(deserializer);
        var var_hasTrack = sse_decode_bool(deserializer);
        return PlayerEvent_State(
          playing: var_playing,
          buffering: var_buffering,
          hasTrack: var_hasTrack,
        );
      case 4:
        var var_action = sse_decode_box_autoadd_media_action(deserializer);
        return PlayerEvent_MediaControl(action: var_action);
      case 5:
        var var_name = sse_decode_String(deserializer);
        var var_sampleRate = sse_decode_u_32(deserializer);
        return PlayerEvent_DeviceChanged(
          name: var_name,
          sampleRate: var_sampleRate,
        );
      case 6:
        var var_message = sse_decode_String(deserializer);
        return PlayerEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TrackSource sse_decode_track_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_cacheKey = sse_decode_opt_String(deserializer);
    var var_formatHint = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_gainDb = sse_decode_f_32(deserializer);
    var var_peak = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_coverKey = sse_decode_opt_String(deserializer);
    return TrackSource(
      id: var_id,
      url: var_url,
      cacheKey: var_cacheKey,
      formatHint: var_formatHint,
      durationMs: var_durationMs,
      gainDb: var_gainDb,
      peak: var_peak,
      title: var_title,
      artist: var_artist,
      album: var_album,
      coverUrl: var_coverUrl,
      coverKey: var_coverKey,
    );
  }

  @protected
  TransitionMode sse_decode_transition_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return TransitionMode_Gapless();
      case 1:
        var var_ms = sse_decode_u_32(deserializer);
        return TransitionMode_Crossfade(ms: var_ms);
      case 2:
        return TransitionMode_Cut();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_player_event_Sse(
    RustStreamSink<PlayerEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_action(
    MediaAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_action(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_player_config(
    PlayerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_player_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_track_source(
    TrackSource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track_source(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transition_mode(
    TransitionMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transition_mode(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_output_device(
    List<OutputDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_output_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_action(MediaAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MediaAction_Play():
        sse_encode_i_32(0, serializer);
      case MediaAction_Pause():
        sse_encode_i_32(1, serializer);
      case MediaAction_Toggle():
        sse_encode_i_32(2, serializer);
      case MediaAction_Next():
        sse_encode_i_32(3, serializer);
      case MediaAction_Previous():
        sse_encode_i_32(4, serializer);
      case MediaAction_Stop():
        sse_encode_i_32(5, serializer);
      case MediaAction_SeekTo(positionMs: final positionMs):
        sse_encode_i_32(6, serializer);
        sse_encode_i_64(positionMs, serializer);
      case MediaAction_SeekBy(deltaMs: final deltaMs):
        sse_encode_i_32(7, serializer);
        sse_encode_i_64(deltaMs, serializer);
      case MediaAction_SetVolume(volume: final volume):
        sse_encode_i_32(8, serializer);
        sse_encode_f_64(volume, serializer);
      case MediaAction_Raise():
        sse_encode_i_32(9, serializer);
      case MediaAction_Quit():
        sse_encode_i_32(10, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_track_source(
    TrackSource? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_track_source(self, serializer);
    }
  }

  @protected
  void sse_encode_output_device(OutputDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDefault, serializer);
  }

  @protected
  void sse_encode_player_config(PlayerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.cacheDir, serializer);
    sse_encode_u_32(self.cacheLimitMb, serializer);
    sse_encode_opt_String(self.deviceId, serializer);
    sse_encode_String(self.appId, serializer);
    sse_encode_String(self.appName, serializer);
    sse_encode_bool(self.mediaControls, serializer);
  }

  @protected
  void sse_encode_player_event(PlayerEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PlayerEvent_TrackStarted(id: final id):
        sse_encode_i_32(0, serializer);
        sse_encode_String(id, serializer);
      case PlayerEvent_TrackEnded(id: final id, error: final error):
        sse_encode_i_32(1, serializer);
        sse_encode_String(id, serializer);
        sse_encode_opt_String(error, serializer);
      case PlayerEvent_Position(
        id: final id,
        positionMs: final positionMs,
        durationMs: final durationMs,
        buffered: final buffered,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(id, serializer);
        sse_encode_i_64(positionMs, serializer);
        sse_encode_opt_box_autoadd_i_64(durationMs, serializer);
        sse_encode_opt_box_autoadd_f_32(buffered, serializer);
      case PlayerEvent_State(
        playing: final playing,
        buffering: final buffering,
        hasTrack: final hasTrack,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_bool(playing, serializer);
        sse_encode_bool(buffering, serializer);
        sse_encode_bool(hasTrack, serializer);
      case PlayerEvent_MediaControl(action: final action):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_media_action(action, serializer);
      case PlayerEvent_DeviceChanged(
        name: final name,
        sampleRate: final sampleRate,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_32(sampleRate, serializer);
      case PlayerEvent_Error(message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_track_source(TrackSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.cacheKey, serializer);
    sse_encode_opt_String(self.formatHint, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
    sse_encode_f_32(self.gainDb, serializer);
    sse_encode_opt_box_autoadd_f_32(self.peak, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_opt_String(self.coverKey, serializer);
  }

  @protected
  void sse_encode_transition_mode(
    TransitionMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TransitionMode_Gapless():
        sse_encode_i_32(0, serializer);
      case TransitionMode_Crossfade(ms: final ms):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(ms, serializer);
      case TransitionMode_Cut():
        sse_encode_i_32(2, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
