// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

/// Inicializa o motor (idempotente: num hot restart só reaproveita).
Future<void> playerInit({required PlayerConfig config}) =>
    RustLib.instance.api.crateApiEnginePlayerInit(config: config);

/// Stream de eventos do motor. Chamar de novo substitui o anterior.
Stream<PlayerEvent> playerEvents() =>
    RustLib.instance.api.crateApiEnginePlayerEvents();

void playerPlay({required TrackSource track, required PlatformInt64 startMs}) =>
    RustLib.instance.api.crateApiEnginePlayerPlay(
      track: track,
      startMs: startMs,
    );

void playerSetNext({TrackSource? track, required TransitionMode mode}) =>
    RustLib.instance.api.crateApiEnginePlayerSetNext(track: track, mode: mode);

void playerPause() => RustLib.instance.api.crateApiEnginePlayerPause();

void playerResume() => RustLib.instance.api.crateApiEnginePlayerResume();

void playerToggle() => RustLib.instance.api.crateApiEnginePlayerToggle();

void playerStop() => RustLib.instance.api.crateApiEnginePlayerStop();

void playerSeek({required PlatformInt64 positionMs}) =>
    RustLib.instance.api.crateApiEnginePlayerSeek(positionMs: positionMs);

void playerSeekBy({required PlatformInt64 deltaMs}) =>
    RustLib.instance.api.crateApiEnginePlayerSeekBy(deltaMs: deltaMs);

void playerSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiEnginePlayerSetVolume(volume: volume);

void playerSetNotifications({required bool enabled}) =>
    RustLib.instance.api.crateApiEnginePlayerSetNotifications(enabled: enabled);

Future<void> playerPrefetch({required TrackSource track}) =>
    RustLib.instance.api.crateApiEnginePlayerPrefetch(track: track);

Future<List<OutputDevice>> playerOutputDevices() =>
    RustLib.instance.api.crateApiEnginePlayerOutputDevices();

Future<void> playerSetOutputDevice({String? deviceId}) => RustLib.instance.api
    .crateApiEnginePlayerSetOutputDevice(deviceId: deviceId);

Future<bool> playerIsCached({required String cacheKey}) =>
    RustLib.instance.api.crateApiEnginePlayerIsCached(cacheKey: cacheKey);

Future<PlatformInt64> playerCacheSize() =>
    RustLib.instance.api.crateApiEnginePlayerCacheSize();

Future<void> playerClearCache() =>
    RustLib.instance.api.crateApiEnginePlayerClearCache();

Future<void> playerSetCacheLimit({required int limitMb}) =>
    RustLib.instance.api.crateApiEnginePlayerSetCacheLimit(limitMb: limitMb);

@freezed
sealed class MediaAction with _$MediaAction {
  const MediaAction._();

  const factory MediaAction.play() = MediaAction_Play;
  const factory MediaAction.pause() = MediaAction_Pause;
  const factory MediaAction.toggle() = MediaAction_Toggle;
  const factory MediaAction.next() = MediaAction_Next;
  const factory MediaAction.previous() = MediaAction_Previous;
  const factory MediaAction.stop() = MediaAction_Stop;
  const factory MediaAction.seekTo({required PlatformInt64 positionMs}) =
      MediaAction_SeekTo;
  const factory MediaAction.seekBy({required PlatformInt64 deltaMs}) =
      MediaAction_SeekBy;
  const factory MediaAction.setVolume({required double volume}) =
      MediaAction_SetVolume;
  const factory MediaAction.raise() = MediaAction_Raise;
  const factory MediaAction.quit() = MediaAction_Quit;
}

class OutputDevice {
  final String id;
  final String name;
  final bool isDefault;

  const OutputDevice({
    required this.id,
    required this.name,
    required this.isDefault,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault;
}

class PlayerConfig {
  final String cacheDir;
  final int cacheLimitMb;
  final String? deviceId;
  final String appId;
  final String appName;
  final bool mediaControls;

  const PlayerConfig({
    required this.cacheDir,
    required this.cacheLimitMb,
    this.deviceId,
    required this.appId,
    required this.appName,
    required this.mediaControls,
  });

  @override
  int get hashCode =>
      cacheDir.hashCode ^
      cacheLimitMb.hashCode ^
      deviceId.hashCode ^
      appId.hashCode ^
      appName.hashCode ^
      mediaControls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerConfig &&
          runtimeType == other.runtimeType &&
          cacheDir == other.cacheDir &&
          cacheLimitMb == other.cacheLimitMb &&
          deviceId == other.deviceId &&
          appId == other.appId &&
          appName == other.appName &&
          mediaControls == other.mediaControls;
}

@freezed
sealed class PlayerEvent with _$PlayerEvent {
  const PlayerEvent._();

  const factory PlayerEvent.trackStarted({required String id}) =
      PlayerEvent_TrackStarted;
  const factory PlayerEvent.trackEnded({required String id, String? error}) =
      PlayerEvent_TrackEnded;
  const factory PlayerEvent.position({
    required String id,
    required PlatformInt64 positionMs,
    PlatformInt64? durationMs,
    double? buffered,
  }) = PlayerEvent_Position;
  const factory PlayerEvent.state({
    required bool playing,
    required bool buffering,
    required bool hasTrack,
  }) = PlayerEvent_State;
  const factory PlayerEvent.mediaControl({required MediaAction action}) =
      PlayerEvent_MediaControl;
  const factory PlayerEvent.deviceChanged({
    required String name,
    required int sampleRate,
  }) = PlayerEvent_DeviceChanged;
  const factory PlayerEvent.error({required String message}) =
      PlayerEvent_Error;
}

class TrackSource {
  /// Identificador único da entrada na fila (volta nos eventos).
  final String id;
  final String url;
  final String? cacheKey;
  final String? formatHint;
  final PlatformInt64? durationMs;

  /// ReplayGain já resolvido (dB), 0 se não houver.
  final double gainDb;
  final double? peak;
  final String title;
  final String artist;
  final String album;
  final String? coverUrl;
  final String? coverKey;

  const TrackSource({
    required this.id,
    required this.url,
    this.cacheKey,
    this.formatHint,
    this.durationMs,
    required this.gainDb,
    this.peak,
    required this.title,
    required this.artist,
    required this.album,
    this.coverUrl,
    this.coverKey,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      url.hashCode ^
      cacheKey.hashCode ^
      formatHint.hashCode ^
      durationMs.hashCode ^
      gainDb.hashCode ^
      peak.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      coverUrl.hashCode ^
      coverKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackSource &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          url == other.url &&
          cacheKey == other.cacheKey &&
          formatHint == other.formatHint &&
          durationMs == other.durationMs &&
          gainDb == other.gainDb &&
          peak == other.peak &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          coverUrl == other.coverUrl &&
          coverKey == other.coverKey;
}

@freezed
sealed class TransitionMode with _$TransitionMode {
  const TransitionMode._();

  const factory TransitionMode.gapless() = TransitionMode_Gapless;
  const factory TransitionMode.crossfade({required int ms}) =
      TransitionMode_Crossfade;
  const factory TransitionMode.cut() = TransitionMode_Cut;
}
