// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Varre as pastas (só relê o que mudou desde o índice) e devolve as faixas.
Future<List<LocalTrack>> libraryScan({
  required List<String> folders,
  required String indexPath,
  required String coversDir,
}) => RustLib.instance.api.crateApiLibraryLibraryScan(
  folders: folders,
  indexPath: indexPath,
  coversDir: coversDir,
);

/// Índice salvo (sem varrer).
Future<List<LocalTrack>> libraryLoad({required String indexPath}) =>
    RustLib.instance.api.crateApiLibraryLibraryLoad(indexPath: indexPath);

/// Arquivos lidos na varredura em andamento.
int libraryScanProgress() =>
    RustLib.instance.api.crateApiLibraryLibraryScanProgress();

class LocalTrack {
  final String path;
  final PlatformInt64 size;
  final PlatformInt64 mtime;
  final String title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? track;
  final int? disc;
  final int? year;
  final String? genre;
  final PlatformInt64? durationMs;
  final int? sampleRate;
  final int? bitDepth;
  final int? channels;
  final int? bitrateKbps;
  final int? bpm;
  final String? cover;
  final double? rgTrackGain;
  final double? rgAlbumGain;
  final double? rgTrackPeak;
  final double? rgAlbumPeak;

  const LocalTrack({
    required this.path,
    required this.size,
    required this.mtime,
    required this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.track,
    this.disc,
    this.year,
    this.genre,
    this.durationMs,
    this.sampleRate,
    this.bitDepth,
    this.channels,
    this.bitrateKbps,
    this.bpm,
    this.cover,
    this.rgTrackGain,
    this.rgAlbumGain,
    this.rgTrackPeak,
    this.rgAlbumPeak,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      size.hashCode ^
      mtime.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      track.hashCode ^
      disc.hashCode ^
      year.hashCode ^
      genre.hashCode ^
      durationMs.hashCode ^
      sampleRate.hashCode ^
      bitDepth.hashCode ^
      channels.hashCode ^
      bitrateKbps.hashCode ^
      bpm.hashCode ^
      cover.hashCode ^
      rgTrackGain.hashCode ^
      rgAlbumGain.hashCode ^
      rgTrackPeak.hashCode ^
      rgAlbumPeak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalTrack &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size &&
          mtime == other.mtime &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          track == other.track &&
          disc == other.disc &&
          year == other.year &&
          genre == other.genre &&
          durationMs == other.durationMs &&
          sampleRate == other.sampleRate &&
          bitDepth == other.bitDepth &&
          channels == other.channels &&
          bitrateKbps == other.bitrateKbps &&
          bpm == other.bpm &&
          cover == other.cover &&
          rgTrackGain == other.rgTrackGain &&
          rgAlbumGain == other.rgAlbumGain &&
          rgTrackPeak == other.rgTrackPeak &&
          rgAlbumPeak == other.rgAlbumPeak;
}
