// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Lê um anúncio baixado.
///
/// `pinned_key` é a chave que o app guardou da primeira vez; passe vazio
/// quando ainda não há nenhuma. Devolve erro (com o motivo em português)
/// quando o anúncio não presta, e nunca aceita um assinado por outra chave.
PortalNotice portalRead({required List<int> raw, required String pinnedKey}) =>
    RustLib.instance.api.crateApiPortalPortalRead(
      raw: raw,
      pinnedKey: pinnedKey,
    );

/// Impressão digital de uma chave já fixada, para mostrar nos Ajustes.
///
/// Mesmo cálculo do `bk-portal link`, para os dois textos baterem quando a
/// pessoa confere de viva voz.
String portalFingerprint({required String key}) =>
    RustLib.instance.api.crateApiPortalPortalFingerprint(key: key);

/// Caminho onde o anúncio fica dentro de um portal.
String portalNoticePath() =>
    RustLib.instance.api.crateApiPortalPortalNoticePath();

/// Tamanho máximo que vale a pena baixar de um anúncio.
int portalMaxBytes() => RustLib.instance.api.crateApiPortalPortalMaxBytes();

/// O que o app aprendeu do anúncio.
class PortalNotice {
  /// Nome que o dono deu ao servidor.
  final String name;

  /// Endereço do Navidrome agora.
  final String music;

  /// Endereço da análise do AutoMix, quando o portal serve uma.
  final String? analysis;

  /// Chave pública de quem assinou, para o app guardar na primeira vez.
  final String key;

  /// A mesma chave em grupos legíveis, para conferir de viva voz.
  final String fingerprint;

  /// Até quando este anúncio vale (segundos desde 1970).
  final BigInt expires;

  const PortalNotice({
    required this.name,
    required this.music,
    this.analysis,
    required this.key,
    required this.fingerprint,
    required this.expires,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      music.hashCode ^
      analysis.hashCode ^
      key.hashCode ^
      fingerprint.hashCode ^
      expires.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortalNotice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          music == other.music &&
          analysis == other.analysis &&
          key == other.key &&
          fingerprint == other.fingerprint &&
          expires == other.expires;
}
