// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Carrega o arquivo de vetores do AudioMuse e o deixa pronto na memória.
/// Devolve quantas músicas ele conhece.
Future<int> recommendLoad({required String path}) =>
    RustLib.instance.api.crateApiRecommendRecommendLoad(path: path);

/// Solta a memória (uns 20 MB) quando não se vai recomendar nada.
Future<void> recommendUnload() =>
    RustLib.instance.api.crateApiRecommendRecommendUnload();

/// Quantas músicas o arquivo carregado conhece (0 = nenhum carregado).
Future<int> recommendCount() =>
    RustLib.instance.api.crateApiRecommendRecommendCount();

/// Esta música tem vetor? (Sem ele não dá para recomendar a partir dela.)
Future<bool> recommendKnows({required String id}) =>
    RustLib.instance.api.crateApiRecommendRecommendKnows(id: id);

/// As mais parecidas com [seed].
///
/// [style]: sound, mood, genre, era, lyrics, mix, server.
/// [allowed] limita o que pode ser sugerido (offline, só o que está baixado);
/// vazio = a biblioteca toda.
Future<List<SimilarSong>> recommendSimilar({
  required String seed,
  required String style,
  required int limit,
  required List<String> allowed,
}) => RustLib.instance.api.crateApiRecommendRecommendSimilar(
  seed: seed,
  style: style,
  limit: limit,
  allowed: allowed,
);

class SimilarSong {
  final String id;
  final double score;

  const SimilarSong({required this.id, required this.score});

  @override
  int get hashCode => id.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarSong &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          score == other.score;
}
